spring.application.name=inventario



spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://143.42.30.41:3307/concenetpro
spring.datasource.username=consultas_concesur
spring.datasource.password=ymCe79-lL1*

#spring.mvc.view.prefix=/static/
#spring.mvc.view.suffix=.html
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false
spring.web.resources.static-locations=classpath:/static/
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoints.enabled-by-default=true
admin.properties.filepath=/opt/app-config/inventario.properties
#admin.properties.filepath=src/main/resources/inventario.properties
app.go.publicado.detail=https://go.grupoconcesur.es/concenet-rest/api/cardInstanceWorkflow/detail/%s/tab/%s
app.go.publicado.editar=https://go.grupoconcesur.es/concenet-rest/api/cardInstanceWorkflow/detail/%s/custom/%s
app.inventarioPRO.apikey=a407365c-858c-4d17-b89a-995c1a822064
app.inventarioPRO.apiUrl=https://data.inventario.pro
app.inventarioPro.gestion=https://gestion.inventario.pro/
app.autoline.baseURL=https://api.eu.keyloop.io
app.autoline.token=${app.autoline.baseURL}/oauth/client_credential/accesstoken?grant_type=client_credentials
app.autoline.reserve=${app.autoline.baseURL}/inventory-vehicles/%s/reserve
app.inventarioPRO.user=concesurgo
app.inventarioPRO.pass=pvCgXmuR7qyqbi@
app.go.fotos.tab=4
app.go.url.adjuntos=https://go.grupoconcesur.es/concenet-rest/api/cardInstanceWorkflow/detail/%s/attachments/%s
app.go.url.download.Adjuntos=https://go.grupoconcesur.es/concenet-rest/api/cardInstanceWorkflow/detail/%s/attachments/4/download/%s
app.inventarioPro.url.addfoto=https://gestion.inventario.pro/coche/addFoto
app.inventarioPro.url.AjaxControlTiempoFotos=https://gestion.inventario.pro/ajax/AjaxControlTiempoFotos
app.inventarioPro.url.signedS3=https://gestion.inventario.pro/coche/signedS3
app.inventarioPro.urlPublicarAnuncio=https://gestion.inventario.pro/ajax/ajaxSaveMultidifusion/
app.inventarioPro.urlBusquedaAnuncio=https://gestion.inventario.pro/coche?matricula=
app.inventarioPro.urlCambioEstadoAnuncio=https://gestion.inventario.pro/ajax/cambioEstadoApi

