app.go.publicadoInv.tab=23
app.go.obtenerVehicleStockId.tab=1
app.g.obtenerResponsableReserva.tab=5
app.url.base=https://go.grupoconcesur.es/concenet-rest/
app.url.token=${app.url.base}api/users/login
app.go.user=bot
app.go.password=sogtulapdt
app.go.Enterprise.Id=29252
app.go.Store.Id=34002180